# Generated by Django 3.2.13 on 2022-07-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_auto_20220720_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.BinaryField(),
        ),
    ]
