# Generated by Django 4.1 on 2022-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('image', models.CharField(max_length=555)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
